import numpy as np


def dtype_i2c_1():
    return np.dtype(
        [
            ("tmicros", "i4"),
            ("d0", "i2"),
            ("d1", "i2"),
            ("d2", "i2"),
            ("e0", "i2"),
            ("e1", "i2"),
            ("e2", "i2"),
            ("f0", "i2"),
            ("f1", "i2"),
            ("f2", "i2"),
            ("c0", "i2"),
            ("a0", "i2"),
            ("a1", "i2"),
            ("a2", "i2"),
            ("b0", "i2"),
            ("b1", "i2"),
            ("b2", "i2"),
            ("gx", "f4"),
            ("gy", "f4"),
            ("gz", "f4"),
            ("wx", "f4"),
            ("wy", "f4"),
            ("wz", "f4"),
            ("Tx", "f4"),
            ("Ty", "f4"),
            ("Tz", "f4"),
            ("gx_i2c", "f4"),
            ("gy_i2c", "f4"),
            ("gz_i2c", "f4"),
            ("wx_i2c", "f4"),
            ("wy_i2c", "f4"),
            ("wz_i2c", "f4"),
            ("Tx_i2c", "f4"),
            ("Ty_i2c", "f4"),
            ("Tz_i2c", "f4"),
        ]
    )


def dtype_i2c_2():
    return np.dtype(
        [
            ("tmicros", "i4"),
            ("d0", "i2"),
            ("d1", "i2"),
            ("d2", "i2"),
            ("f0", "i2"),
            ("f1", "i2"),
            ("f2", "i2"),
            ("a0", "i2"),
            ("a1", "i2"),
            ("a2", "i2"),
            ("b0", "i2"),
            ("b1", "i2"),
            ("b2", "i2"),
            ("gx", "f4"),
            ("gy", "f4"),
            ("gz", "f4"),
            ("wx", "f4"),
            ("wy", "f4"),
            ("wz", "f4"),
            ("Tx", "f4"),
            ("Ty", "f4"),
            ("Tz", "f4"),
            ("gx_i2c_c", "f4"),
            ("gy_i2c_c", "f4"),
            ("gz_i2c_c", "f4"),
            ("wx_i2c_c", "f4"),
            ("wy_i2c_c", "f4"),
            ("wz_i2c_c", "f4"),
            ("Tx_i2c_c", "f4"),
            ("Ty_i2c_c", "f4"),
            ("Tz_i2c_c", "f4"),
            ("gx_i2c_e", "f4"),
            ("gy_i2c_e", "f4"),
            ("gz_i2c_e", "f4"),
            ("wx_i2c_e", "f4"),
            ("wy_i2c_e", "f4"),
            ("wz_i2c_e", "f4"),
            ("Tx_i2c_e", "f4"),
            ("Ty_i2c_e", "f4"),
            ("Tz_i2c_e", "f4"),
        ]
    )


def dtype_std():
    return np.dtype(
        [
            ("tmicros", "i4"),
            ("d0", "i2"),
            ("d1", "i2"),
            ("d2", "i2"),
            ("e0", "i2"),
            ("e1", "i2"),
            ("e2", "i2"),
            ("f0", "i2"),
            ("f1", "i2"),
            ("f2", "i2"),
            ("c0", "i2"),
            ("c1", "i2"),
            ("c2", "i2"),
            ("a0", "i2"),
            ("a1", "i2"),
            ("a2", "i2"),
            ("b0", "i2"),
            ("b1", "i2"),
            ("b2", "i2"),
            ("gx", "f4"),
            ("gy", "f4"),
            ("gz", "f4"),
            ("wx", "f4"),
            ("wy", "f4"),
            ("wz", "f4"),
            ("Tx", "f4"),
            ("Ty", "f4"),
            ("Tz", "f4"),
        ]
    )


FIRMWARE_DTYPES = {
    "i2c_2": dtype_i2c_2,
    "i2c_1": dtype_i2c_1,
    "std": dtype_std,
}

COLUMN_ORDERS = {
    "i2c_2": [
        "tmicros",
        "t",
        "a0",
        "a1",
        "a2",
        "b0",
        "b1",
        "b2",
        "d0",
        "d1",
        "d2",
        "f0",
        "f1",
        "f2",
        "gx",
        "gy",
        "gz",
        "wx",
        "wy",
        "wz",
        "Tx",
        "Ty",
        "Tz",
        "gx_i2c_c",
        "gy_i2c_c",
        "gz_i2c_c",
        "wx_i2c_c",
        "wy_i2c_c",
        "wz_i2c_c",
        "Tx_i2c_c",
        "Ty_i2c_c",
        "Tz_i2c_c",
        "gx_i2c_e",
        "gy_i2c_e",
        "gz_i2c_e",
        "wx_i2c_e",
        "wy_i2c_e",
        "wz_i2c_e",
        "Tx_i2c_e",
        "Ty_i2c_e",
        "Tz_i2c_e",
    ],
    "i2c_1": [
        "tmicros",
        "t",
        "a0",
        "a1",
        "a2",
        "b0",
        "b1",
        "b2",
        "c0",
        "d0",
        "d1",
        "d2",
        "e0",
        "e1",
        "e2",
        "f0",
        "f1",
        "f2",
        "gx",
        "gy",
        "gz",
        "wx",
        "wy",
        "wz",
        "Tx",
        "Ty",
        "Tz",
        "gx_i2c",
        "gy_i2c",
        "gz_i2c",
        "wx_i2c",
        "wy_i2c",
        "wz_i2c",
        "Tx_i2c",
        "Ty_i2c",
        "Tz_i2c",
    ],
    "std": [
        "tmicros",
        "t",
        "a0",
        "a1",
        "a2",
        "b0",
        "b1",
        "b2",
        "c0",
        "c1",
        "c2",
        "d0",
        "d1",
        "d2",
        "e0",
        "e1",
        "e2",
        "f0",
        "f1",
        "f2",
        "gx",
        "gy",
        "gz",
        "wx",
        "wy",
        "wz",
        "Tx",
        "Ty",
        "Tz",
    ],
}
